/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internalPages;

import com.toedter.calendar.JDateChooser;
import config.dbconfiguration;
import static internalPages.AddEditBlotter.sched;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author HP
 */
public class Blotter extends javax.swing.JInternalFrame {

    /**
     * Creates new form Blotter
     */
    public Blotter() {
        initComponents();
        displayData();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
    }
  
    public void displayData(){
        try{
            dbconfiguration dbc = new dbconfiguration();
            ResultSet rs = dbc.getData("SELECT b_caseno, b_accusation, b_schedule, complainantlastname, cfirstname, cmiddle, respondentlastname, rfirstname, rmiddle, b_status FROM blotter");
            blotter.setModel(DbUtils.resultSetToTableModel(rs));
            DefaultTableModel model = (DefaultTableModel) blotter.getModel();
            String[] columnIdentifiers = {"Case NO", "Accusation", "Schedule", "ComplainantLastname", "Firstname", "Middle", "RespondentLastname", "Firstname", "Middle", "Status"};
            model.setColumnIdentifiers(columnIdentifiers);
            
             rs.close();
        }catch(SQLException ex){
            System.out.println("Errors: "+ex.getMessage());
        
        }
        }
    
        Color navcolor= new Color(255,102,102);
        Color headcolor= new Color(255,153,153);
        Color bodycolor = new Color(255,204,204);

        
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        db = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        blotter = new javax.swing.JTable();
        edit = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        add = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        delete = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        print = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        display = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        db.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsFolder/blotter (1).png"))); // NOI18N
        jPanel2.add(db, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 50));

        jLabel24.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("BLOTTER");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 140, 50));

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 20, 190, 50);

        jScrollPane1.setViewportView(blotter);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 160, 860, 300);

        edit.setBackground(new java.awt.Color(255, 153, 153));
        edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editMouseExited(evt);
            }
        });
        edit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsFolder/edit (1).png"))); // NOI18N
        edit.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        jLabel10.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("EDIT");
        edit.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 80, 40));

        jPanel1.add(edit);
        edit.setBounds(20, 110, 130, 40);

        add.setBackground(new java.awt.Color(255, 153, 153));
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addMouseExited(evt);
            }
        });
        add.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsFolder/add (1).png"))); // NOI18N
        add.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        jLabel11.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("ADD");
        add.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 80, 40));

        jPanel1.add(add);
        add.setBounds(160, 110, 130, 40);

        delete.setBackground(new java.awt.Color(255, 153, 153));
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteMouseExited(evt);
            }
        });
        delete.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsFolder/delete (1).png"))); // NOI18N
        delete.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        jLabel12.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("DELETE");
        delete.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 80, 40));

        jPanel1.add(delete);
        delete.setBounds(300, 110, 130, 40);

        print.setBackground(new java.awt.Color(255, 153, 153));
        print.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsFolder/print1 (1).png"))); // NOI18N
        print.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        jLabel9.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("PRINT");
        print.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 80, 40));

        jPanel1.add(print);
        print.setBounds(570, 110, 130, 40);

        display.setBackground(new java.awt.Color(255, 153, 153));
        display.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                displayMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                displayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                displayMouseExited(evt);
            }
        });
        display.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsFolder/display (1).png"))); // NOI18N
        display.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        jLabel18.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("DISPLAY");
        display.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 80, 40));

        jPanel1.add(display);
        display.setBounds(440, 110, 120, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseEntered
     edit.setBackground(navcolor);
    }//GEN-LAST:event_editMouseEntered

    private void editMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseExited
      edit.setBackground(headcolor);
    }//GEN-LAST:event_editMouseExited

    private void addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseEntered
        add.setBackground(navcolor);
    }//GEN-LAST:event_addMouseEntered

    private void addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseExited
        add.setBackground(headcolor);
    }//GEN-LAST:event_addMouseExited

    private void deleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseEntered
        delete.setBackground(navcolor);
    }//GEN-LAST:event_deleteMouseEntered

    private void deleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseExited
       delete.setBackground(headcolor);
    }//GEN-LAST:event_deleteMouseExited

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
       JFrame mainFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        mainFrame.dispose();
        AddEditBlotter bl = new AddEditBlotter();
        bl.setVisible(true);
        bl.action = "Add";
        bl.st_label.setText("SAVE");      
    }//GEN-LAST:event_addMouseClicked

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        int rowIndex = blotter.getSelectedRow();
       if(rowIndex < 0){
           JOptionPane.showMessageDialog(null, "Please select data first from the table!");
       }else{
            TableModel model = blotter.getModel();
            Object value = model.getValueAt(rowIndex, 0);
            String id = value.toString();   
             int a=JOptionPane.showConfirmDialog(null,"Are you sure to delete ID "+id);  
                    if(a==JOptionPane.YES_OPTION){  
                            dbconfiguration dbc = new dbconfiguration();
                            int b_id=Integer.parseInt(id);
                            dbc.deleteddData(b_id,"blotter");
                            displayData();
                            
                    }    
       }
    }//GEN-LAST:event_deleteMouseClicked

    private void editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseClicked
     
        int rowIndex = blotter.getSelectedRow();
        if (rowIndex < 0) {
            JOptionPane.showMessageDialog(null, "Please Select an Item!");
        } else {
            TableModel model = blotter.getModel();
            AddEditBlotter blo = new AddEditBlotter();
            blo.id.setText("" + model.getValueAt(rowIndex, 0));
            String bid = model.getValueAt(rowIndex, 0).toString();
        try {
           
        dbconfiguration dbc = new dbconfiguration();
        ResultSet rs = dbc.getData("SELECT * FROM blotter WHERE b_id = '" + bid + "'");

        if (rs.next()) {
            blo.caseno.setText(rs.getString("b_caseno"));
            blo.accusation.setText(rs.getString("b_accusation"));
            
           String date = rs.getString("b_schedule");   
           ((JTextField)sched.getDateEditor().getUiComponent()).setText(date);
           
            blo.clastname.setText(rs.getString("complainantlastname"));
            blo.cfirstname.setText(rs.getString("cfirstname"));
            blo.cmiddle.setText(rs.getString("cmiddle"));
            
            blo.rlastname.setText(rs.getString("respondentlastname"));
            blo.rfirstname.setText(rs.getString("rfirstname"));
            blo.rmiddle.setText(rs.getString("rmiddle"));
            
            blo.status.setSelectedItem(rs.getString("b_status"));
 
                blo.setVisible(true);
                blo.action = "Update";
                blo.st_label.setText("UPDATE");
              
                JFrame mainFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
                mainFrame.dispose();
       
            }
        
    } catch (SQLException e) {
        System.out.println("" + e);
    }
}
        
        /*int rowIndex = blotter.getSelectedRow();
        if (rowIndex < 0) {
            JOptionPane.showMessageDialog(null, "Please Select an Item!");
        } else {
            TableModel model = blotter.getModel();
            AddEditBlotter bl = new AddEditBlotter();
            bl.id.setText("" + model.getValueAt(rowIndex, 0));
            String bid = model.getValueAt(rowIndex, 0).toString();
        try {
           
        dbconfiguration dbc = new dbconfiguration();
        
        ResultSet rs = dbc.getData("SELECT * FROM blotter WHERE b_id = '" + bid + "'");

        if (rs.next()) {
            bl.caseno.setText(rs.getString("b_caseno"));
            bl.accusation.setText(rs.getString("b_accusation"));  
            
            String date = rs.getString("b_schedule");   
            
            bl.status.setSelectedItem(rs.getString("b_status"));
            bl.complain.setText(rs.getString("b_complainant"));
            bl.respondent.setText(rs.getString("b_respondent"));
            
            ((JTextField)sched.getDateEditor().getUiComponent()).setText(date);
        }       
        
        
        
    } catch (SQLException e) {
        System.out.println("" + e);
    }
}*/

    }//GEN-LAST:event_editMouseClicked

    private void displayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_displayMouseClicked
        displayData();
    }//GEN-LAST:event_displayMouseClicked

    private void displayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_displayMouseEntered
        display.setBackground(navcolor);
    }//GEN-LAST:event_displayMouseEntered

    private void displayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_displayMouseExited
        display.setBackground(headcolor);
    }//GEN-LAST:event_displayMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel add;
    private javax.swing.JTable blotter;
    private javax.swing.JLabel db;
    private javax.swing.JPanel delete;
    private javax.swing.JPanel display;
    private javax.swing.JPanel edit;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel print;
    // End of variables declaration//GEN-END:variables
}
