/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internalPages;

import java.awt.Color;
import java.awt.print.PrinterException;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author HP
 */
public class residentRecords extends javax.swing.JInternalFrame {

    /**
     * Creates new form residentRecords
     */
    public residentRecords() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
    }
    
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        search = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_priority = new javax.swing.JTable();
        search1 = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        firstname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lastname = new javax.swing.JTextField();
        status = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        gender = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        voterstatus = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        addRow = new javax.swing.JButton();
        printreport = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(null);

        search.setBackground(new java.awt.Color(255, 153, 153));
        search.setFont(new java.awt.Font("Baskerville Old Face", 0, 16)); // NOI18N
        jPanel1.add(search);
        search.setBounds(20, 10, 240, 30);

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jButton1.setText("CLEAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(130, 50, 90, 30);

        tbl_priority.setBackground(new java.awt.Color(255, 153, 153));
        tbl_priority.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Milinda", "Requinto", "Female", "50", "Married", "Registered"},
                {"2", "Ronald", "Teremocha", "Male", "53", "Married", "Registered"},
                {"3", "Marcel", "Garan", "Female", "58", "Married", "Registered"},
                {"4", "Milodia", "Traya", "Female", "59", "Married", "Registered"},
                {"5", "Binibinida", "Genabe", "Female", "52", "Married", "Registered"},
                {"6", "Victorio", "Iglesia", "Male", "51", "Married", "Registered"},
                {"7", "Maribeth", "Aligado", "Female", "56", "Married", "Registered"},
                {"8", "Cecilia", "Villacensio", "Female", "49", "Married", "Registered"},
                {"9", "Estrella", "Caliñada", "Female", "46", "Married", "Registered"},
                {"10", "Luda", "Geraldez", "Female", "47", "Married", "Registered"}
            },
            new String [] {
                "ID", "FIRST NAME", "LAST NAME", "GENDER", "AGE", "STATUS", "VOTER STATUS"
            }
        ));
        tbl_priority.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_priorityMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_priority);
        if (tbl_priority.getColumnModel().getColumnCount() > 0) {
            tbl_priority.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(250, 80, 620, 340);

        search1.setBackground(new java.awt.Color(255, 102, 102));
        search1.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        search1.setText("SEARCH");
        search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search1ActionPerformed(evt);
            }
        });
        jPanel1.add(search1);
        search1.setBounds(20, 50, 100, 30);

        update.setBackground(new java.awt.Color(255, 102, 102));
        update.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update);
        update.setBounds(140, 370, 100, 30);

        jLabel3.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        jLabel3.setText("Resident ID:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 90, 70, 30);

        id.setBackground(new java.awt.Color(255, 153, 153));
        id.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        jPanel1.add(id);
        id.setBounds(100, 90, 140, 30);

        firstname.setBackground(new java.awt.Color(255, 153, 153));
        firstname.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameActionPerformed(evt);
            }
        });
        jPanel1.add(firstname);
        firstname.setBounds(100, 130, 140, 30);

        jLabel4.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        jLabel4.setText("First Name:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 130, 90, 30);

        jLabel5.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        jLabel5.setText("Last Name:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 170, 90, 30);

        lastname.setBackground(new java.awt.Color(255, 153, 153));
        lastname.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameActionPerformed(evt);
            }
        });
        jPanel1.add(lastname);
        lastname.setBounds(100, 170, 140, 30);

        status.setBackground(new java.awt.Color(255, 153, 153));
        status.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });
        jPanel1.add(status);
        status.setBounds(100, 290, 140, 30);

        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        jLabel2.setText("Status:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 290, 90, 30);

        jLabel6.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        jLabel6.setText("Gender:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 210, 90, 30);

        jLabel7.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        jLabel7.setText("Age:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 250, 90, 30);

        gender.setBackground(new java.awt.Color(255, 153, 153));
        gender.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderActionPerformed(evt);
            }
        });
        jPanel1.add(gender);
        gender.setBounds(100, 210, 140, 30);

        age.setBackground(new java.awt.Color(255, 153, 153));
        age.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageActionPerformed(evt);
            }
        });
        jPanel1.add(age);
        age.setBounds(100, 250, 140, 30);

        jLabel8.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        jLabel8.setText("Voter Status:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 330, 90, 30);

        voterstatus.setBackground(new java.awt.Color(255, 153, 153));
        voterstatus.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        voterstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voterstatusActionPerformed(evt);
            }
        });
        jPanel1.add(voterstatus);
        voterstatus.setBounds(100, 330, 140, 30);

        jButton2.setBackground(new java.awt.Color(255, 102, 102));
        jButton2.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(20, 370, 110, 30);

        delete.setBackground(new java.awt.Color(255, 102, 102));
        delete.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete);
        delete.setBounds(20, 410, 110, 30);

        addRow.setBackground(new java.awt.Color(255, 102, 102));
        addRow.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        addRow.setText("ADD");
        addRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRowActionPerformed(evt);
            }
        });
        jPanel1.add(addRow);
        addRow.setBounds(140, 410, 100, 30);

        printreport.setBackground(new java.awt.Color(255, 102, 102));
        printreport.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        printreport.setText("PRINT REPORT");
        printreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printreportActionPerformed(evt);
            }
        });
        jPanel1.add(printreport);
        printreport.setBounds(700, 40, 160, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        search.setText(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search1ActionPerformed
        DefaultTableModel model = (DefaultTableModel) tbl_priority.getModel();
        TableRowSorter<DefaultTableModel> obj  = new TableRowSorter<>(model);
        tbl_priority.setRowSorter(obj);
        obj.setRowFilter(RowFilter.regexFilter(search.getText()));    
    }//GEN-LAST:event_search1ActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        int i = tbl_priority.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)tbl_priority.getModel();
        if(i >= 0 )
        {
            model.setValueAt(id.getText(), i, 0);
            model.setValueAt(firstname.getText(), i, 1);
            model.setValueAt(lastname.getText(), i, 2);
            model.setValueAt(gender.getText(), i, 3);
            model.setValueAt(age.getText(), i, 4);
            model.setValueAt(status.getText(), i, 5);
            model.setValueAt(voterstatus.getText(), i, 6);
        }else{
            JOptionPane.showMessageDialog(null, "ERROR!");
        }
    }//GEN-LAST:event_updateActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameActionPerformed

    private void lastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameActionPerformed

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusActionPerformed

    private void genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderActionPerformed

    private void ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageActionPerformed

    private void voterstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voterstatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_voterstatusActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        id.setText(null);
        firstname.setText(null);
        lastname.setText(null);
        gender.setText(null);
        age.setText(null);
        status.setText(null);
        voterstatus.setText(null);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        DefaultTableModel model = (DefaultTableModel) tbl_priority.getModel();
        try{
            int SelectedRowIndex = tbl_priority.getSelectedRow();
            model.removeRow(SelectedRowIndex);
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void addRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRowActionPerformed
        DefaultTableModel model = (DefaultTableModel) tbl_priority.getModel();
        model.addRow(new Object[]{id.getText(), firstname.getText(),
            lastname.getText(), gender.getText(),age.getText(), status.getText(), voterstatus.getText() });
    }//GEN-LAST:event_addRowActionPerformed

    private void printreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printreportActionPerformed
        MessageFormat header = new MessageFormat("PUROK INFORMATION SYSTEM");
        MessageFormat footer = new MessageFormat("Tagbuag-tubig, Tagjaguimit City of Naga, Cebu");
        try{
            tbl_priority.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        }catch(PrinterException e){
            JOptionPane.showMessageDialog(null, "Cannot be print!"+e.getMessage());
        }

    }//GEN-LAST:event_printreportActionPerformed

    private void tbl_priorityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_priorityMouseClicked
        int selectedRow = tbl_priority.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tbl_priority.getModel();
        id.setText(model.getValueAt(selectedRow, 0).toString());
        firstname.setText(model.getValueAt(selectedRow, 1).toString());
        lastname.setText(model.getValueAt(selectedRow, 2).toString());
        gender.setText(model.getValueAt(selectedRow, 3).toString());
        age.setText(model.getValueAt(selectedRow, 4).toString());
        status.setText(model.getValueAt(selectedRow, 5).toString());
        voterstatus.setText(model.getValueAt(selectedRow, 6).toString());
        
        
    }//GEN-LAST:event_tbl_priorityMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRow;
    private javax.swing.JTextField age;
    private javax.swing.JButton delete;
    private javax.swing.JTextField firstname;
    private javax.swing.JTextField gender;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastname;
    private javax.swing.JButton printreport;
    private javax.swing.JTextField search;
    private javax.swing.JButton search1;
    private javax.swing.JTextField status;
    private javax.swing.JTable tbl_priority;
    private javax.swing.JButton update;
    private javax.swing.JTextField voterstatus;
    // End of variables declaration//GEN-END:variables
}
